### ISSUE TITLE
If one library rejects, the Promise chain rejects

### ISSUE THREAD

**Issue by devolt5** [memowe/script-importer#1]
The current implementation has a problem with not resolving libraries. If one Promise rejects, none of the following libraries are loaded. We need to cover the scenario, that there is no dependency in libraries and that we can load all libs parallel.

Suggestion with different method signature:
```javascript
 // Works with an array of URLs or a simple URL given as string
  import(libraries = [], isSequential = false) {
    if (typeof libraries === "string") return this.importSingle(libraries);
    if (isSequential)
      return libraries.reduce(
        (a, b) => a.then(() => this.importSingle(b)),
        Promise.resolve()
      );
    return Promise.all(libraries.map((l) => this.importSingle(l)));
  }
```

**Comment by memowe** [comment]
Thank you very much for your issue, @devolt5! This makes a lot of sense. I see two approaches here:

## Option 1: do nothing

For the sake of code and documentaition simplicity, we could ignore the problem of a possibly breaking dependency loading chain as a broken dependency would probably break your code anyway.

## Option 2: go one step further

As your code proposal contains code for parallel *and* sequential loading, I would prefer to go one step further and allow both parallel and sequential dependency loading at the same time. Instead of the `isSequential` switch, we could design this by a list of parallel dependencies, each item being either a single URL string or an array of dependencies, that should be loaded as a chain:

Two dependencies, loading in parallel:

    si.import(URL1, URL2);

In parallel: single dependency URL and a sequential dependency chain:

    si.import(
        URL1,
        [URL2a, URL2b],
    );

Please feel free to contribute a pull request, @devolt5! :)

**Comment by memowe** [comment]
@devolt5 Please have a look at #3
